import { Container } from 'pixi.js';

/**
 * HUD Layout Manifest — SSoT for per-element HUD layout editing.
 *
 * Each entry is one logical, individually-movable HUD element. The box
 * (x, y, w, h) is in BASE 640x360 coordinates (uiScale = 1) and describes
 * where the element appears ON SCREEN by default. It drives:
 *   1. The HUD editor tool (game/tools/hud-tool) draws a draggable rect here.
 *   2. HUD.applyLayout() uses the box center as the default scale/pivot anchor.
 *
 * The override layer lives in a SEPARATE file (hud_layout.json), NOT in the
 * Aseprite atlas. The atlas `bounds` is the PNG sampling rectangle (dual
 * purpose: texture frame + default screen anchor) and is regenerated by
 * ase-export, so it must stay untouched. Overrides apply on top: HUD wraps
 * each element's display object(s) in a per-element Container and shifts/
 * scales/hides that container. With an empty override (offset 0, scale 1,
 * pivot center, visible true) the HUD is pixel-identical to the un-edited
 * build, on both the skin path and the Graphics fallback.
 *
 * Consumed by: HUD.ts (applyLayout / applySkin), hud-tool.html, hud_layout.json.
 */

/** Which render path an element uses (informational, for the editor). */
export type HudElementKind = 'skin' | 'graphics';

/** Editor grouping for the side panel. */
export type HudElementGroup = 'status' | 'map' | 'world' | 'itemworld' | 'popup';

/** A single element's default on-screen footprint in base 640x360 space. */
export interface HudElement {
  /** Stable id — the key in hud_layout.json. */
  id: string;
  /** Human-readable label shown in the editor. */
  label: string;
  /** Editor grouping. */
  group: HudElementGroup;
  /** Render path. */
  kind: HudElementKind;
  /** Default screen box (base 640x360 coords, uiScale = 1). */
  x: number;
  y: number;
  w: number;
  h: number;
}

/** Per-element override stored in hud_layout.json. All fields optional. */
export interface HudElementOverride {
  /** Horizontal shift in base units (multiplied by uiScale on apply). */
  offsetX?: number;
  /** Vertical shift in base units (multiplied by uiScale on apply). */
  offsetY?: number;
  /** Uniform scale around the pivot. Default 1. */
  scale?: number;
  /** Pivot X within the element box, normalized 0..1. Default 0.5 (center). */
  pivotX?: number;
  /** Pivot Y within the element box, normalized 0..1. Default 0.5 (center). */
  pivotY?: number;
  /** false hides the element. Default true. */
  visible?: boolean;
}

/** The full layout document persisted to game/public/data/hud_layout.json. */
export interface HudLayout {
  /** Schema version for forward-compat. */
  version: number;
  /** Overrides keyed by HudElement.id. Missing keys = default. */
  elements: Record<string, HudElementOverride>;
}

export function applyHudElementLayout(
  target: Container,
  box: HudElement,
  override: HudElementOverride,
  mult: number,
): void {
  const pivotX = (box.x + box.w * (override.pivotX ?? 0.5)) * mult;
  const pivotY = (box.y + box.h * (override.pivotY ?? 0.5)) * mult;
  target.pivot.set(pivotX, pivotY);
  target.position.set(
    pivotX + (override.offsetX ?? 0) * mult,
    pivotY + (override.offsetY ?? 0) * mult,
  );
  target.scale.set(override.scale ?? 1);
  if (override.visible === false) target.visible = false;
}

export function createOrGetHudLayoutWrapper(
  wrappers: Map<string, Container>,
  id: string,
  parent: Container,
): Container {
  let wrapper = wrappers.get(id);
  if (!wrapper) {
    wrapper = new Container();
    wrapper.sortableChildren = true;
    parent.addChild(wrapper);
    wrappers.set(id, wrapper);
  }
  return wrapper;
}

/** Canonical base screen dimensions the boxes are authored against. */
export const HUD_BASE_W = 640;
export const HUD_BASE_H = 360;

/** Schema version stamped into freshly-created layout documents. */
export const HUD_LAYOUT_VERSION = 1;

/**
 * The editable HUD elements. Boxes are the on-screen footprint at uiScale = 1,
 * derived from HUD.ts (applySkin screen placement + Graphics constructor
 * constants). Boxes for dynamically-sized rows (flasks, action keys, depth,
 * EXP) are approximate — precision is not load-bearing since live rendering
 * comes from HUD.ts, and pivot can be nudged in the editor.
 *
 * `id` values are also used directly as HUD.applyLayout() wrapper keys.
 */
export const HUD_ELEMENTS: readonly HudElement[] = [
  // ----- Status block (top-left), skin path -----
  { id: 'statusFrame',   label: 'Status Frame',   group: 'status', kind: 'skin',     x: 4,   y: 7,   w: 162, h: 51 },
  { id: 'portraitFrame', label: 'Portrait',       group: 'status', kind: 'skin',     x: 13,  y: 11,  w: 35,  h: 33 },
  { id: 'hpBar',         label: 'HP Bar',         group: 'status', kind: 'skin',     x: 66,  y: 16,  w: 90,  h: 13 },
  { id: 'hpText',        label: 'HP Text',        group: 'status', kind: 'skin',     x: 54,  y: 15,  w: 30,  h: 13 },
  { id: 'flaskKey',      label: 'Flask [R] Key',  group: 'status', kind: 'skin',     x: 98,  y: 31,  w: 12,  h: 12 },
  { id: 'flaskIcons',    label: 'Flask Icons',    group: 'status', kind: 'skin',     x: 56,  y: 32,  w: 42,  h: 9  },
  { id: 'atkText',       label: 'ATK Text',       group: 'status', kind: 'skin',     x: 98,  y: 49,  w: 64,  h: 18 },

  // ----- Map block (top-right), skin path -----
  { id: 'mapFrame',      label: 'Minimap Frame',  group: 'map',    kind: 'skin',     x: 515, y: 6,   w: 118, h: 65 },
  { id: 'itemKey',       label: 'Item [I] Key',   group: 'map',    kind: 'skin',     x: 594, y: 73,  w: 18,  h: 17 },
  { id: 'mapKey',        label: 'Map [M] Key',    group: 'map',    kind: 'skin',     x: 615, y: 73,  w: 18,  h: 17 },

  // ----- World HUD (Graphics, always present) -----
  { id: 'gold',          label: 'Gold',           group: 'world',  kind: 'graphics', x: 582, y: 8,   w: 50,  h: 11 },
  { id: 'bossBar',       label: 'Boss HP',        group: 'world',  kind: 'graphics', x: 248, y: 12,  w: 144, h: 22 },
  { id: 'statusIcons',   label: 'Status Icons',   group: 'world',  kind: 'graphics', x: 254, y: 6,   w: 20,  h: 18 },
  { id: 'egoShards',     label: 'Ego Shards',     group: 'world',  kind: 'graphics', x: 120, y: 24,  w: 34,  h: 12 },

  // ----- Item World only -----
  { id: 'actionKeys',    label: 'Action Keys',    group: 'world',  kind: 'skin',     x: 9,   y: 300, w: 122, h: 46 },
  { id: 'depthFrame',    label: 'Depth Gauge',    group: 'itemworld', kind: 'skin',  x: 25,  y: 61,  w: 11,  h: 133 },
  { id: 'expBar',        label: 'Item EXP',       group: 'itemworld', kind: 'graphics', x: 6, y: 68, w: 120, h: 26 },
  { id: 'itemExitHint',  label: 'Exit Hint',      group: 'itemworld', kind: 'graphics', x: 580, y: 20, w: 54, h: 16 },

  // ----- Popups (event-driven; offset/scale only, never auto-hidden) -----
  // Bottom-center one-shot key hint (TutorialHint). Width is content-sized;
  // box is a representative default centered on GAME_WIDTH/2.
  { id: 'tutorialHint',  label: 'Tutorial Hint',  group: 'popup',  kind: 'graphics', x: 250, y: 273, w: 140, h: 40 },
  // Bottom full-width dialogue / lore box (LoreDisplay).
  { id: 'dialogue',      label: 'Dialogue Box',   group: 'popup',  kind: 'graphics', x: 0,   y: 248, w: 640, h: 64 },
] as const;

/** Look up an element's box by id. */
export function getHudElement(id: string): HudElement | undefined {
  return HUD_ELEMENTS.find((e) => e.id === id);
}
